packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: 3.24.2
  next: ^15.1.5
  "@types/node": ^22.10.5
  react: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  typescript: ^5.7.2
  vitest: ^2.1.8
  remeda: ^2.20.1
  "@t3-oss/env-core": 0.11.1
  "@t3-oss/env-nextjs": 0.11.1
  "@anatine/zod-mock": ^3.13.5
  "@faker-js/faker": ^9.3.0
  prisma: ~6.1.0
  "@prisma/client": ~6.1.0
